import {useEffect,useState} from 'react';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {request} from './api';

type Status={configured:boolean;received:{total:number;lastReceived:string|null};state:null|{status:string;lastAttempt:string|null;lastSuccess:string|null;nextRun:string|null;message:string};errors:{eventId:string|null;sourceInquiryId:string|null;status:number;message:string;lastSeen:string}[]};
const date=(s:string|null)=>s?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'}).format(new Date(s)):'기록 없음';
const labels:Record<string,string>={idle:'다음 확인 대기',running:'확인 중',needs_review:'오류 확인 필요',blocked:'인증 확인 필요',retry:'재시도 대기'};
export function Integrations({role}:{role:string}){
  const [data,setData]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
  async function load(){try{setData(await request('/admin/integrations/emergent'));setError('');}catch(e){setError((e as Error).message);}}
  useEffect(()=>{if(role!=='admin')return;void load();const timer=setInterval(()=>void load(),15000);return()=>clearInterval(timer);},[role]);
  async function run(resume=false){if(busy)return;setBusy(true);setError('');try{await request(`/admin/integrations/emergent/${resume?'resume':'recover'}`,'POST',resume?{confirmed}:{});setConfirmed(false);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(role!=='admin')return <p role="alert">외부 문의 연결은 관리자만 확인할 수 있습니다.</p>;
  return <div className="grid min-w-0 gap-5"><h1 className="text-2xl font-semibold">외부 문의 연결</h1><p className="text-sm text-muted-foreground">Emergent 문의 수신과 누락 보충 상태를 확인합니다.</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{data&&<><Card className="min-w-0 gap-3 p-5"><h2 className="font-semibold">누락 보충 · {data.configured?'연결 설정됨':'연결 준비 전'}</h2><p className="text-sm">{data.configured?'원본 목록에서 누락된 문의를 확인합니다. 저장되지 않은 문의가 있으면 조회 위치를 넘기지 않습니다.':'실제 Emergent 주소와 인증 정보가 아직 연결되지 않았습니다. 현재 외부 문의를 자동으로 가져오지는 않습니다.'}</p><p className="text-sm">저장된 외부 문의 {data.received.total}건 · 마지막 수신 {date(data.received.lastReceived)}</p><p className="text-sm">마지막 보충 성공: {date(data.state?.lastSuccess??null)}</p>{data.state&&<><p className="text-sm">처리 상태: {labels[data.state.status]||data.state.status}</p><p className="text-sm">{data.state.message}</p><p className="text-xs text-muted-foreground">최근 시도 {date(data.state.lastAttempt)} · 다음 확인 {date(data.state.nextRun)}</p></>}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void load()}>상태 새로 확인</Button><Button disabled={!data.configured||busy||data.state?.status==='blocked'} onClick={()=>void run()}>누락 확인 실행</Button></div>{data.state?.status==='blocked'&&<div className="grid gap-3 border-t pt-4"><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>관리자가 만료된 인증 정보를 점검하고 연결 설정을 수정했습니다.</label><Button disabled={!data.configured||!confirmed||busy} onClick={()=>void run(true)}>확인 후 복구 재개</Button></div>}</Card><section className="grid min-w-0 gap-3"><h2 className="font-semibold">확인이 필요한 수신 오류</h2>{!data.errors.length&&<p className="text-sm text-muted-foreground">기록된 오류가 없습니다.{!data.configured?' 아직 실제 연결 검사를 수행한 것은 아닙니다.':''}</p>}{data.errors.map((e,i)=><Card className="min-w-0 gap-2 p-4" key={i}><p className="break-all text-sm">문의 ID: {e.sourceInquiryId||'형식 확인 필요'}</p><p className="text-sm">{e.message}</p><p className="text-xs text-muted-foreground">최근 확인 {date(e.lastSeen)} · 오류 {e.status}</p></Card>)}<p className="text-xs text-muted-foreground">미해결 오류 중 최근 100개를 표시합니다. 원문을 수정한 후 같은 조회 위치에서 다시 확인하면 중복 생성 없이 복구합니다.</p></section></>}</div>;
}
