import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect } from '@/components/ui/native-select';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { TASK_TYPES, taskTypeGroups } from '../../../../packages/domain/task-types';
import { createId } from '../../../../packages/domain/id';
import { STAGES, type Stage } from '../../../../packages/domain/crm';
import { request, RequestError } from './api';
import { Notifications } from './Notifications';
import { OperatingSettings, FirstContactMetrics } from './Operations';
import {useLiveChanges} from './useLiveChanges';
import {Integrations} from './Integrations';
import {Accounts} from './Accounts';
import { AiWorkflowDemo } from './AiWorkflowDemo';
import { CaseActions, ChangeSummary, isCaseClosed, type CaseData, type Proposal } from './CaseActions';

type User = {id:string;name:string;email:string;role:'admin'|'staff'};
type Case = CaseData;
type Task = {id:string;caseId:string;title:string;kind:'first'|'work';dueAt:string|null;originalDueAt:string|null;status:string;excluded:boolean;completedAt:string|null;version:number;caseName?:string;assigneeName?:string;request?:string};
type Detail = {salesCase:Case;proposals:Proposal[];tasks:Task[];notes:{id:string;body:string;author:string;at:string}[];activities:{id:string;action:string;author:string;at:string;payload:Record<string,unknown>}[]};
type Board = {missingNext:Case[];attentionCount:number;overdue:Task[];today:Task[];upcoming:Task[];needsReview:Task[];now:string};
type Editor = {kind:'record'|'due'|'reopen'|'exclude'|'task'|'note';task?:Task;caseId:string;caseVersion:number;stage:Stage};
const fmt=(value:string|null)=>value?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)):'기한 확인 필요';
const localTime=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,19);
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid min-w-0 gap-2 text-sm font-medium">{label}{children}</label>;}
function Notice({children}:{children:ReactNode}){return <p role="status" className="rounded-md border bg-muted/40 p-4 text-sm leading-relaxed">{children}</p>;}
function ErrorText({message}:{message:string}){return message?<p role="alert" className="rounded-md border border-destructive/30 p-3 text-sm text-destructive">{message}</p>:null;}

export function LiveApp(){
  const location = useLocation();
  return location.pathname === '/live/ai-demo' ? <AiWorkflowDemo/> : <LiveWorkspace/>;
}

function LiveWorkspace(){
  useEffect(()=>{document.title='고객 업무 관리 · 실제 저장 검수';},[]);
  const [user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [board,setBoard]=useState<Board|null>(null),[cases,setCases]=useState<Case[]>([]),[detail,setDetail]=useState<Detail|null>(null);
  const [editor,setEditor]=useState<Editor|null>(null),[message,setMessage]=useState(''),[view,setView]=useState('today'),[search,setSearch]=useState('');
  const location=useLocation(),navigate=useNavigate();const sequence=useRef(0);
  const isInquiry=location.pathname==='/live/inquiry';const caseId=/^\/live\/cases\/([^/]+)$/.exec(location.pathname)?.[1];
  useEffect(()=>{request('/auth/me').then(r=>setUser(r.user)).catch(e=>{if(e.status!==401)setError(e.message);}).finally(()=>setBoot(false));},[]);
  const load=useCallback(async()=>{
    if(!user||isInquiry)return;
    const seq=++sequence.current;setBusy(true);setError('');
    try{
      if(caseId){const r=await request(`/cases/${caseId}`);if(seq===sequence.current)setDetail(r);}
      else if(location.pathname==='/live/cases'){const r=await request(`/cases?search=${encodeURIComponent(search)}`);if(seq===sequence.current)setCases(r.items);}
      else if(['/live/notifications','/live/settings','/live/metrics','/live/integrations','/live/accounts'].includes(location.pathname)){return;} else {const r=await request('/workboard');if(seq===sequence.current)setBoard(r);}
    }catch(e){const err=e as RequestError;if(seq===sequence.current){setError(err.message);if(err.status===401)setUser(null);if(err.status===401||err.status===404)setDetail(null);}}
    finally{if(seq===sequence.current)setBusy(false);}
  },[user,isInquiry,caseId,location.pathname,search]);
  useEffect(()=>{setDetail(null);void load();},[load]);
  const liveEnabled=!!user&&!isInquiry&&!['/live/notifications','/live/settings','/live/metrics','/live/integrations','/live/accounts'].includes(location.pathname);
  const liveState=useLiveChanges(liveEnabled,load,()=>{setUser(null);setBoard(null);setCases([]);setDetail(null);setError('로그인 상태가 변경되었습니다. 다시 로그인해 주세요.');});
  async function editTask(task:Task,kind:Editor['kind']){
    setError('');try{const r:Detail=await request(`/cases/${task.caseId}`);const fresh=r.tasks.find(t=>t.id===task.id);if(fresh)setEditor({kind,task:fresh,caseId:task.caseId,caseVersion:r.salesCase.version,stage:r.salesCase.stage});}catch(e){setError((e as Error).message);}
  }
  const card=(task:Task)=><Card key={task.id} className="min-w-0 max-w-full gap-3 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><Link className="text-sm underline" to={`/live/cases/${task.caseId}`}>{task.caseName||detail?.salesCase.name}</Link><Badge variant={task.dueAt&&Date.parse(task.dueAt)<Date.now()?'destructive':'secondary'}>{task.dueAt?Date.parse(task.dueAt)<Date.now()?'기한 초과':'미완료':'기한 확인 필요'}</Badge></div><h3 className="break-words font-semibold">{task.title}</h3><p className="truncate text-sm text-muted-foreground" title={task.request||detail?.salesCase.original.memo}>초기 요청 · {task.request||detail?.salesCase.original.memo}</p><p className="text-xs text-muted-foreground">{fmt(task.dueAt)} · {task.assigneeName||detail?.salesCase.assigneeName}</p><div className="flex flex-wrap justify-end gap-2">{!isCaseClosed(detail?.salesCase.stage||'')&&<><Button variant="outline" size="sm" onClick={()=>void editTask(task,'due')}>{task.dueAt?'기한 변경':'기한 설정'}</Button><Button size="sm" onClick={()=>void editTask(task,'record')}>{task.kind==='first'?'지금 연락하기':'지금 처리하기'}</Button>{caseId&&<Button variant="ghost" size="sm" onClick={()=>void editTask(task,'exclude')}>관리 제외</Button>}</>}</div></Card>;
  return <div className="min-h-screen bg-background text-foreground"><header className="border-b"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3 px-4 py-4"><Link to="/live" className="font-semibold">고객 업무 관리</Link><Badge variant="outline">6.1 · MVP 구축 중</Badge><Link to="/live/ai-demo" className="text-sm underline">AI 업무 정리 시연</Link>{user&&<div className="flex items-center gap-3 text-sm"><span>{user.name} · {user.role==='admin'?'관리자':'직원'}</span><Button variant="outline" size="sm" onClick={async()=>{try{await request('/auth/logout','POST');setUser(null);setEditor(null);setBoard(null);setCases([]);setDetail(null);navigate('/live');}catch(e){setError((e as Error).message);}}}>로그아웃</Button></div>}</div></header>
    <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6">
      <p className="mb-5 text-xs leading-relaxed text-muted-foreground">저장한 기록은 서버에 보관됩니다. 현재는 시험 사용 단계로 예시 정보를 입력해 주세요. 전화·문자는 직접 수행한 뒤 기록하며, 이메일·AI·외부 문의 연동은 아직 연결 전입니다.</p>
      {isInquiry?<LiveInquiry/>:boot?<Notice>로그인 상태를 확인하고 있습니다.</Notice>:!user?<><ErrorText message={error}/><Login onLogin={u=>{setUser(u);setBoard(null);setDetail(null);setCases([]);setError('');}}/></>:<>
        <nav className="mb-6 flex flex-wrap gap-2" aria-label="실제 저장 업무 메뉴">{[['오늘 할 일','/live'],['영업건','/live/cases'],['상담 접수','/live/inquiry'],['알림·실행 내역','/live/notifications'],['첫 연락 성과','/live/metrics'],...(user.role==='admin'?[['운영 기준','/live/settings'],['직원 계정','/live/accounts'],['외부 문의 연결','/live/integrations']]:[])].map(([label,url])=><Link key={url} className={`rounded-md border px-4 py-2 text-sm ${location.pathname===url?'bg-primary text-primary-foreground':'hover:bg-muted'}`} to={url}>{label}</Link>)}{!['/live/notifications','/live/settings','/live/metrics','/live/integrations','/live/accounts'].includes(location.pathname)&&<Button variant="ghost" disabled={busy} onClick={()=>void load()}>새로 불러오기</Button>}</nav>
        {liveEnabled&&<p role="status" className="mb-4 text-xs text-muted-foreground">{liveState==='live'?'업무 변경을 자동으로 반영하고 있습니다.':liveState==='retrying'?'실시간 연결을 복구하고 있습니다. 15초마다 최신 내용을 확인합니다.':'업무 변경 알림에 연결하고 있습니다.'}</p>}
        <ErrorText message={error}/>{message&&<div className="mb-4"><Notice>{message}</Notice></div>}
        {caseId?detail?<><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">{detail.salesCase.name}</h1><Badge variant="secondary">{detail.salesCase.stage}</Badge></div><div className="mb-6 flex flex-wrap gap-3 rounded-md border p-4 text-xs">{STAGES.slice(0,6).map((s,i)=><span key={s} className={s===detail.salesCase.stage?'font-bold':'text-muted-foreground'}>{i+1}. {s}</span>)}</div><CaseActions salesCase={detail.salesCase} proposals={detail.proposals||[]} role={user.role} onSaved={load}/><div className="grid items-start gap-6 lg:grid-cols-[1fr_280px]"><div className="grid min-w-0 gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">업무와 다음 할 일</h2><Button disabled={isCaseClosed(detail.salesCase.stage)} onClick={()=>setEditor({kind:'task',caseId,caseVersion:detail.salesCase.version,stage:detail.salesCase.stage})}>다음 할 일 등록</Button></div>{detail.tasks.filter(t=>t.status==='incomplete'&&!t.excluded).map(card)}{!isCaseClosed(detail.salesCase.stage)&&!detail.tasks.some(t=>t.status==='incomplete'&&!t.excluded)&&<Notice>진행 중인 고객입니다. 다음 할 일이나 다시 확인할 날짜를 등록해 주세요.</Notice>}<details className="rounded-md border p-4"><summary className="cursor-pointer text-sm">완료·관리 제외 기록 {detail.tasks.filter(t=>t.status==='complete'||t.excluded).length}</summary><div className="mt-3 grid gap-3">{detail.tasks.filter(t=>t.status==='complete'||t.excluded).map(t=><div className="flex flex-wrap items-center justify-between gap-2 text-sm" key={t.id}><div>{t.title}<p className="text-xs text-muted-foreground">{t.excluded?'관리 제외':`완료 · ${fmt(t.completedAt)}`}</p></div>{!t.excluded&&!isCaseClosed(detail.salesCase.stage)&&<Button variant="outline" size="sm" onClick={()=>void editTask(t,'reopen')}>완료 취소</Button>}</div>)}</div></details>
          <div className="mt-4 flex items-center justify-between gap-3"><h2 className="font-semibold">상담 메모</h2><Button disabled={isCaseClosed(detail.salesCase.stage)} variant="outline" onClick={()=>setEditor({kind:'note',caseId,caseVersion:detail.salesCase.version,stage:detail.salesCase.stage})}>메모 작성</Button></div>{detail.notes.length?detail.notes.map(n=><Card key={n.id} className="gap-2 p-4"><p className="whitespace-pre-wrap break-words text-sm">{n.body}</p><p className="text-xs text-muted-foreground">{n.author} · {fmt(n.at)}</p></Card>):<Notice>아직 작성한 메모가 없습니다.</Notice>}
          <h2 className="mt-4 font-semibold">변경 이력</h2>{detail.activities.map(a=><Card key={a.id} className="gap-2 p-4"><strong className="text-sm">{a.action}</strong><ChangeSummary payload={a.payload}/><p className="text-xs text-muted-foreground">{a.author} · {fmt(a.at)}</p>{!!a.payload.reason&&<p className="text-sm">이유: {String(a.payload.reason)}</p>}{!!a.payload.outcome&&<p className="text-sm">결과: {{connected:'통화 연결',sms:'부재 후 문자 발송',attempt:'전화만 시도',completed:'업무 완료'}[String(a.payload.outcome)]}</p>}</Card>)}
        </div><Card className="gap-4 p-5"><h2 className="font-semibold">고객 정보</h2><dl className="grid gap-3 text-sm">{[['고객 담당자',detail.salesCase.person],['연락처',detail.salesCase.phone],['이메일',detail.salesCase.email],['우리 담당자',detail.salesCase.assigneeName],['접수 시각',fmt(detail.salesCase.receivedAt)]].map(([label,value])=><div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-all">{value}</dd></div>)}</dl><div><h3 className="text-sm font-medium">고객 요청 내용 · 수정본</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm">{detail.salesCase.requestMemo}</p></div><details><summary className="text-sm">초기 요청 원문</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm">{detail.salesCase.original.memo}</p></details></Card></div></>:<Notice>{busy?'영업건을 불러오는 중입니다.':'영업건을 표시할 수 없습니다.'}</Notice>
        :location.pathname==='/live/accounts'?<Accounts role={user.role}/>:location.pathname==='/live/settings'?<OperatingSettings role={user.role}/>:location.pathname==='/live/integrations'?<Integrations role={user.role}/>:location.pathname==='/live/metrics'?<FirstContactMetrics/>:location.pathname==='/live/notifications'?<Notifications/>:location.pathname==='/live/cases'?<><h1 className="mb-4 text-2xl font-semibold">영업건</h1><Input className="mb-4 max-w-md" aria-label="영업건 검색" placeholder="고객명, 담당자, 초기 요청 검색" value={search} onChange={e=>setSearch(e.target.value)}/><p className="mb-4 text-xs text-muted-foreground">접근 가능한 최근 영업건 최대 100개</p><div className="grid gap-4 sm:grid-cols-2">{cases.map(c=><Link key={c.id} className="min-w-0" to={`/live/cases/${c.id}`}><Card className="gap-2 p-5 hover:bg-muted/30"><div className="flex flex-wrap justify-between gap-2"><strong>{c.name}</strong><Badge variant="secondary">{c.stage}</Badge></div><p className="truncate text-sm">초기 요청 · {c.original.memo}</p><p className="text-xs text-muted-foreground">{c.assigneeName} · {fmt(c.receivedAt)}</p></Card></Link>)}</div>{!cases.length&&!busy&&<Notice>조건에 맞는 영업건이 없습니다.</Notice>}</>
        :<><h1 className="mb-2 text-2xl font-semibold">오늘 할 일</h1><p className="mb-5 text-sm text-muted-foreground">실제 현재 시각 · {board?fmt(board.now):'불러오는 중'} (한국 시간)</p><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['기한 초과',board?.overdue.length||0],['오늘 확인',board?.today.length||0],['기한 확인',board?.needsReview.length||0],['다음 할 일 등록 필요',board?.missingNext?.length||0]].map(([label,count])=><Card className="gap-2 p-4" key={label}><span className="text-xs text-muted-foreground">{label}</span><strong className="text-2xl">{count}</strong></Card>)}</div><div className="mb-5 flex gap-2"><Button variant={view==='today'?'default':'outline'} onClick={()=>setView('today')}>오늘 업무</Button><Button variant={view==='upcoming'?'default':'outline'} onClick={()=>setView('upcoming')}>예정 업무</Button></div>{board&&(view==='today'?[['기한이 지난 업무',board.overdue],['오늘 확인할 업무',board.today],['기한 확인 필요',board.needsReview]]:[['예정 업무',board.upcoming]]).map(([label,list])=><section className="mb-6" key={String(label)}><h2 className="mb-3 font-semibold">{String(label)} · {(list as Task[]).length}</h2><div className="grid gap-3">{(list as Task[]).map(card)}</div>{!(list as Task[]).length&&<Notice>해당하는 미완료 업무가 없습니다.</Notice>}</section>)}{view==='today'&&board&&<section className="mb-6"><h2 className="mb-3 font-semibold">다음 할 일 등록 필요 · {board.missingNext?.length||0}건</h2><div className="grid gap-3">{board.missingNext?.map(c=><Card key={c.id} className="min-w-0 gap-3 p-4"><Link className="font-medium underline" to={`/live/cases/${c.id}`}>{c.name}</Link><p className="truncate text-sm text-muted-foreground">초기 요청 · {c.original.memo}</p><p className="text-sm">진행 중인 고객입니다. 다음 할 일이나 다시 확인할 날짜를 등록해 주세요.</p><Button className="self-end" variant="outline" onClick={async()=>{try{const fresh:Detail=await request(`/cases/${c.id}`);setEditor({kind:'task',caseId:c.id,caseVersion:fresh.salesCase.version,stage:fresh.salesCase.stage});}catch(e){setError((e as Error).message);}}}>다음 할 일 등록</Button></Card>)}</div>{!board.missingNext?.length&&<Notice>다음 할 일 등록이 필요한 고객이 없습니다.</Notice>}</section>}{!!board?.attentionCount&&<Link className="mb-4 block text-sm text-destructive underline" to="/live/notifications">자동 처리 확인 필요 · {board.attentionCount}건</Link>}{board&&!board.missingNext?.length&&Object.values({a:board.overdue,b:board.today,c:board.upcoming,d:board.needsReview}).every(t=>!t.length)&&<Link className="text-sm underline" to="/live/inquiry">첫 상담을 접수해서 검수 시작하기</Link>}</>}
      </>}
    </main>
    {editor&&<LiveEditor authenticated={!!user} key={`${editor.kind}:${editor.task?.id||editor.caseId}`} editor={editor} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);setMessage('서버에 저장했습니다. 새로고침해도 기록이 유지됩니다.');await load();}} onExpired={()=>setUser(null)}/>}
  </div>;
}

function Login({onLogin}:{onLogin:(u:User)=>void}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  return <Card className="mx-auto max-w-md gap-5 p-6"><h1 className="text-2xl font-semibold">로그인</h1><p className="text-sm text-muted-foreground">안내받은 계정으로 로그인하세요. 역할은 서버에 저장된 계정으로 결정됩니다.</p><form className="grid gap-4" onSubmit={async e=>{e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');try{const r=await request('/auth/login','POST',{email:form.get('email'),password:form.get('password')});onLogin(r.user);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Field label="이메일"><Input name="email" type="email" required autoComplete="username"/></Field><Field label="비밀번호"><Input name="password" type="password" required autoComplete="current-password"/></Field><ErrorText message={error}/><Button disabled={busy}>{busy?'확인 중…':'로그인'}</Button></form><Link className="text-sm underline" to="/live/inquiry">고객 상담 접수 화면</Link></Card>;
}
function LiveInquiry(){
  const [kind,setKind]=useState('company'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<{receiptId:string;firstContactDueAt:string}|null>(null);
  const key=useRef(createId());
  return <Card className="mx-auto max-w-2xl gap-5 p-6"><h1 className="text-2xl font-semibold">{receipt?'상담 요청을 접수했습니다':'신규 상담 요청'}</h1>{receipt?<><Notice>첫 연락 기한: {fmt(receipt.firstContactDueAt)} · 담당자에게 배정되었습니다. 접수 확인 이메일은 아직 연결 전입니다.</Notice><p className="break-all text-xs text-muted-foreground">접수 번호: {receipt.receiptId}</p><Link className="underline" to="/live">직원 업무 화면으로 이동</Link><Button variant="outline" onClick={()=>{setReceipt(null);key.current=createId();}}>다른 상담 접수</Button></>:<form className="grid gap-5" onChange={()=>{key.current=createId();}} onSubmit={async e=>{
    e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');
    try{setReceipt(await request('/public/inquiries/local-review','POST',{customerType:kind,name:f.get('name'),person:kind==='company'?f.get('person'):'',phone:f.get('phone'),email:f.get('email'),size:f.get('size')||'',memo:f.get('memo')},key.current));}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }}><Field label="신청 유형"><NativeSelect value={kind} onChange={e=>setKind(e.target.value)}><option value="company">회사·업체</option><option value="person">개인</option></NativeSelect></Field><Field label={kind==='company'?'회사·업체명':'이름'}><Input name="name" required maxLength={200}/></Field>{kind==='company'&&<Field label="고객 담당자명"><Input name="person" required maxLength={200}/></Field>}<div className="grid gap-4 sm:grid-cols-2"><Field label="연락처"><Input name="phone" type="tel" required maxLength={30}/></Field><Field label="이메일"><Input name="email" type="email" required maxLength={254}/></Field></div>{kind==='company'&&<Field label="회사 규모 (선택)"><NativeSelect name="size">{['미정','1명','2~9명','10~49명','50~299명','300명 이상'].map(s=><option key={s}>{s}</option>)}</NativeSelect></Field>}<Field label="상담 내용"><Textarea name="memo" required maxLength={4000} rows={4} placeholder="요청하시는 서비스와 연락 가능한 시간을 알려주세요."/></Field><ErrorText message={error}/><Button disabled={busy}>{busy?'접수 중…':'상담 요청'}</Button><p className="text-xs text-muted-foreground">첫 구축 검수용입니다. 예시 정보를 입력해 주세요. 실제 전화·문자는 발송하지 않습니다.</p></form>}</Card>;
}
function LiveEditor({editor:e,authenticated,onClose,onSaved,onExpired}:{editor:Editor;authenticated:boolean;onClose:()=>void;onSaved:()=>Promise<void>;onExpired:()=>void}){
  const [values,setValues]=useState<Record<string,string>>({taskType:'',description:'',date:e.task?.dueAt?new Date(Date.parse(e.task.dueAt)+9*3600000).toISOString().slice(0,10):'',reason:'',body:'',memo:'',outcome:'',actualAt:localTime()});
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(e.task?.version||e.caseVersion);const key=useRef(createId());
  const [conflict,setConflict]=useState(false),[latestSummary,setLatestSummary]=useState('');
  function field(name:string,value:string){setValues(v=>({...v,[name]:value}));key.current=createId();}
  const options=taskTypeGroups(e.stage);const label={task:'다음 할 일 등록',note:'상담 메모 작성',record:e.task?.kind==='first'?'첫 연락 결과 기록':'업무 완료 기록',due:'기한 설정·변경',reopen:'완료 취소',exclude:'업무 관리 제외'}[e.kind];
  async function save(event:FormEvent){
    event.preventDefault();if(busy)return;setBusy(true);setError('');setConflict(false);
    try{
      let path='',method='POST',body:Record<string,unknown>={expectedVersion:version};
      if(e.kind==='task'){path=`/cases/${e.caseId}/tasks`;body={...body,taskType:values.taskType,description:values.description,date:values.date};}
      if(e.kind==='note'){path=`/cases/${e.caseId}/notes`;body={...body,body:values.body};}
      if(e.kind==='record'){
        body={...body,actualAt:new Date(`${values.actualAt}+09:00`).toISOString(),memo:values.memo};
        if(e.task?.kind==='first'){path=`/cases/${e.caseId}/contacts`;body={...body,taskId:e.task.id,outcome:values.outcome};}
        else path=`/tasks/${e.task?.id}/complete`;
      }
      if(e.kind==='due'){path=`/tasks/${e.task?.id}`;method='PATCH';body={...body,date:values.date,reason:values.reason};}
      if(e.kind==='reopen'||e.kind==='exclude'){path=`/tasks/${e.task?.id}/${e.kind}`;body={...body,reason:values.reason};}
      await request(path,method,body,key.current);await onSaved();
    }catch(err){const failure=err as RequestError;setError(failure.message);setConflict(failure.status===409);if(failure.status===401)onExpired();}finally{setBusy(false);}
  }
  return <Dialog open={authenticated} onOpenChange={open=>{if(!open&&!busy&&authenticated)onClose();}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogTitle>{label}</DialogTitle><DialogDescription>입력한 내용은 서버에 저장되며 변경 이력에 남습니다.</DialogDescription><form className="grid gap-4" onSubmit={save}>
    {e.kind==='task'&&<><Field label="어떤 업무인가요?"><NativeSelect required value={values.taskType} onChange={event=>field('taskType',event.target.value)}><option value="">업무 종류를 선택하세요</option><optgroup label={`현재 단계 · ${e.stage}`}>{options.recommended.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</optgroup><optgroup label="다른 단계의 업무">{options.others.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</optgroup><option value="other">기타 고객 관련 업무</option></NativeSelect></Field><Field label={`구체적인 내용 ${values.taskType==='other'?'(필수)':'(선택)'}`}><Textarea required={values.taskType==='other'} value={values.description} onChange={event=>field('description',event.target.value)} maxLength={1000}/></Field><Field label="처리할 날짜 (선택)"><Input type="date" value={values.date} onChange={event=>field('date',event.target.value)}/></Field><Notice>{TASK_TYPES.find(t=>t.id===values.taskType)?.label||'업무 종류를 선택하세요'}{values.description.trim()?` · ${values.description.trim()}`:''}<br/>날짜가 없으면 ‘기한 확인 필요’로 저장합니다.</Notice></>}
    {e.kind==='note'&&<Field label="상담 메모"><Textarea required value={values.body} onChange={event=>field('body',event.target.value)} maxLength={4000}/></Field>}
    {e.kind==='record'&&<><Notice>직접 연락하거나 업무를 수행한 뒤 결과를 기록하세요. 저장만으로 전화·문자가 발송되지 않습니다.</Notice>{e.task?.kind==='first'&&<Field label="연락 결과"><NativeSelect required value={values.outcome} onChange={event=>field('outcome',event.target.value)}><option value="">결과를 선택하세요</option><option value="connected">통화 연결</option><option value="sms">부재 후 안내 문자 발송</option><option value="attempt">전화만 시도 · 문자 미발송</option></NativeSelect></Field>}<Field label="실제 수행 시각 (한국 시간)"><Input type="datetime-local" step={1} required value={values.actualAt} onChange={event=>field('actualAt',event.target.value)}/></Field><Field label="상담 메모 (선택)"><Textarea value={values.memo} onChange={event=>field('memo',event.target.value)} maxLength={4000}/></Field></>}
    {e.kind==='due'&&<><Notice>원래 기한: {fmt(e.task?.originalDueAt||null)} · 변경해도 원래 기한은 보존됩니다.</Notice><Field label="처리할 날짜"><Input type="date" required value={values.date} onChange={event=>field('date',event.target.value)}/></Field></>}
    {['due','reopen','exclude'].includes(e.kind)&&<Field label="변경 이유"><Textarea required value={values.reason} onChange={event=>field('reason',event.target.value)} maxLength={1000}/></Field>}
    <ErrorText message={error}/>{latestSummary&&<Notice>{latestSummary}</Notice>}{conflict&&<Button type="button" variant="outline" disabled={busy} onClick={async()=>{try{const latest:Detail=await request(`/cases/${e.caseId}`);const task=latest.tasks.find(t=>t.id===e.task?.id);setVersion(e.task?task?.version||version:latest.salesCase.version);setLatestSummary(task?`최신 업무: ${task.title} / ${task.excluded?'관리 제외':task.status==='complete'?'완료':'미완료'} / 기한 ${fmt(task.dueAt)}. 아래 입력과 비교 후 저장하세요.`:`최신 단계: ${latest.salesCase.stage}, 업무 ${latest.tasks.length}개, 메모 ${latest.notes.length}개. 내용을 확인하고 저장하세요.`);key.current=createId();setError('');setConflict(false);}catch(err){setError((err as Error).message);}}}>최신 버전 확인 · 입력 유지</Button>}
    <div className="flex justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>닫기</Button><Button disabled={busy}>{busy?'저장 중…':'저장'}</Button></div>
  </form></DialogContent></Dialog>;
}
