import {useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {Card} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect} from '@/components/ui/native-select';
import {createId} from '../../../../packages/domain/id';
import {request,RequestError} from './api';
import {Backups} from './Backups';
const date=(s:string)=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s));
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid min-w-0 gap-2 text-sm font-medium">{label}{children}</label>;}
type Setting={companyName:string;defaultAssigneeId:string;holidays:string[];version:number;users:{id:string;name:string;active:boolean}[];history:{id:string;actor:string;reason:string;at:string;before:{defaultAssigneeId:string;holidays:string[]};after:{defaultAssigneeId:string;holidays:string[]}}[]};
export function OperatingSettings({role}:{role:string}){
  const [data,setData]=useState<Setting|null>(null),[assignee,setAssignee]=useState(''),[holidays,setHolidays]=useState(''),[reason,setReason]=useState('');
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[conflict,setConflict]=useState(false),[latestShown,setLatestShown]=useState(false);
  const key=useRef(createId());
  async function load(keepInput=false){setBusy(true);try{const r:Setting=await request('/admin/settings');setData(r);if(!keepInput){setAssignee(r.defaultAssigneeId||'');setHolidays(r.holidays.join('\n'));}setConfirmed(false);setConflict(false);setLatestShown(keepInput);key.current=createId();setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{if(role==='admin')void load();},[role]);
  const changed=()=>{key.current=createId();setConfirmed(false);setMessage('');};
  async function save(e:FormEvent){e.preventDefault();if(!data||busy)return;setBusy(true);setError('');try{await request('/admin/settings','PATCH',{defaultAssigneeId:assignee,holidays:holidays.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),reason,confirmed,expectedVersion:data.version},key.current);await load();setReason('');setMessage('운영 기준을 저장했습니다. 기존 영업건의 담당자와 기한은 유지됩니다.');}catch(err){setError((err as Error).message);setConflict(err instanceof RequestError&&err.status===409);}finally{setBusy(false);}}
  if(role!=='admin')return <p role="alert">운영 기준은 관리자 계정에서 설정할 수 있습니다.</p>;
  return <div className="grid gap-5"><h1 className="text-2xl font-semibold">운영 기준</h1><p className="text-sm text-muted-foreground">신규 상담의 담당자와 영업일 계산에 사용할 회사 휴일을 관리합니다.</p>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm">{message}</p>}{data&&<><Card className="min-w-0 gap-4 p-5"><h2 className="font-semibold">{data.companyName}</h2><form onSubmit={save}><fieldset disabled={busy} className="grid min-w-0 gap-5"><Field label="신규 상담 기본 담당자"><NativeSelect required value={assignee} onChange={e=>{setAssignee(e.target.value);changed();}}><option value="">선택하세요</option>{data.users.map(u=><option key={u.id} value={u.id} disabled={!u.active}>{u.name}{u.active?'':' · 비활성'}</option>)}</NativeSelect></Field><Field label="회사 휴일 (선택)"><Textarea value={holidays} rows={6} onChange={e=>{setHolidays(e.target.value);changed();}} placeholder={'날짜를 한 줄에 하나씩 입력하세요.\n예: 2026-12-25'} /></Field><p className="text-xs text-muted-foreground">YYYY-MM-DD 형식으로 입력합니다. 토요일·일요일은 자동으로 제외됩니다. 법정 공휴일이 자동 등록되지는 않습니다.</p><div className="rounded-md border bg-muted/40 p-4 text-sm">첫 연락 기한: 접수일 다음 영업일 17시 · 한국 시간<br/>정기 알림: 영업일 15시 / 16시 30분<br/>이 값들은 이번 MVP의 고정 기준입니다.</div><Field label="변경 이유"><Textarea required maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);changed();}}/></Field><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>담당자·첫 연락 기한 변경은 새로 접수되는 상담부터 적용되며, 휴일에 따른 정기 알림 일정은 즉시 적용됨을 확인했습니다.</label>{conflict&&<Button variant="outline" type="button" onClick={()=>void load(true)}>최신 설정 확인 · 입력 유지</Button>}{latestShown&&<div className="rounded-md border p-4 text-sm">최신 담당자: {data.users.find(u=>u.id===data.defaultAssigneeId)?.name}<br/>최신 휴일: {data.holidays.join(', ')||'없음'}<p className="mt-2">위에 남아 있는 입력과 비교한 뒤 다시 확인해 주세요.</p></div>}<Button disabled={busy||!confirmed} className="justify-self-end">{busy?'저장 중…':'운영 기준 저장'}</Button></fieldset></form></Card><section className="grid min-w-0 gap-3"><h2 className="font-semibold">운영 기준 변경 이력</h2>{!data.history.length&&<p className="text-sm text-muted-foreground">아직 변경 기록이 없습니다.</p>}{data.history.map(h=><Card key={h.id} className="min-w-0 gap-2 p-4"><p className="break-words text-sm">{h.reason}</p><p className="text-xs text-muted-foreground">{h.actor} · {date(h.at)}</p><details><summary className="cursor-pointer text-sm">변경 내용 보기</summary><p className="mt-2 text-sm">담당자: {data.users.find(u=>u.id===h.before.defaultAssigneeId)?.name||'기록 확인 필요'} → {data.users.find(u=>u.id===h.after.defaultAssigneeId)?.name||'기록 확인 필요'}</p><p className="break-words text-sm">휴일: {h.before.holidays.join(', ')||'없음'} → {h.after.holidays.join(', ')||'없음'}</p></details></Card>)}</section><Backups/></>}</div>;
}

type Metric={from:string;to:string;asOf:string;denominator:number;onTime:number;late:number;incomplete:number;notYetDue:number;connected:number;sms:number;excluded:number;rate:number|null;totalItems:number;items:{id:string;name:string;stage:string;assignee:string;originalDueAt:string;completedAt:string|null;result:string;excluded:boolean}[]};
const results:Record<string,string>={on_time:'기한 내 완료',late:'기한 후 완료',incomplete:'미완료·관리 제외',not_yet_due:'아직 기한 전'};
export function FirstContactMetrics(){
  const today=new Date(Date.now()+9*3600000).toISOString().slice(0,10),[from,setFrom]=useState(`${today.slice(0,7)}-01`),[to,setTo]=useState(today);
  const [data,setData]=useState<Metric|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){setBusy(true);setError('');try{setData(await request(`/metrics/first-contact?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{void load();},[]);
  return <div className="grid min-w-0 gap-5"><h1 className="text-2xl font-semibold">첫 연락 성과</h1><p className="text-sm text-muted-foreground">목표는 원래 기한 이내 첫 연락 완료율 100%입니다. 관리자에게는 회사 전체, 직원에게는 현재 담당 영업건이 표시됩니다.</p><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void load();}}><Field label="기한 조회 시작일"><Input type="date" required value={from} onInput={e=>setFrom(e.currentTarget.value)} onChange={e=>setFrom(e.target.value)}/></Field><Field label="기한 조회 종료일"><Input type="date" required value={to} onInput={e=>setTo(e.currentTarget.value)} onChange={e=>setTo(e.target.value)}/></Field><Button disabled={busy}>{busy?'조회 중…':'조회'}</Button></form>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{data&&<><p className="text-xs text-muted-foreground">적용 기간: {data.from} ~ {data.to} · 집계 시각 {date(data.asOf)}</p><div className="grid min-w-0 gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card className="min-w-0 gap-2 p-5"><span className="text-sm">기한 내 완료율</span><strong className="text-2xl">{data.rate===null?'집계 대상 없음':`${Math.floor(data.rate*10)/10}%`}</strong><span className="text-xs text-muted-foreground">{data.onTime} / {data.denominator}건 · 목표 100%</span></Card>{[['기한 내 완료',data.onTime],['기한 후 완료',data.late],['미완료·관리 제외',data.incomplete]].map(([label,n])=><Card className="min-w-0 gap-2 p-5" key={label}><span className="text-sm">{label}</span><strong className="text-2xl">{n}건</strong></Card>)}</div><Card className="min-w-0 gap-3 p-5"><h2 className="font-semibold">산정 기준 · 검수안</h2><p className="text-sm">조회 기간에 접수 당시 원래 기한이 속하고, 집계 시각까지 기한이 도래한 상담을 집계합니다. 기한 변경이나 영업건 종료로 기존 지연 실적이 사라지지 않습니다.</p><p className="text-sm">통화 연결 또는 부재 후 안내 문자 발송을 완료로 인정합니다. 전화 시도만 한 경우는 미완료입니다. 대상 제외 기준은 아직 확정 전이므로 관리 제외한 건도 분모에 포함합니다.</p><p className="text-sm">집계 대상 중 통화 연결 완료 {data.connected}건 · 문자 발송 완료 {data.sms}건 · 관리 제외 {data.excluded}건</p><p className="text-sm">조회 기간에 있지만 아직 기한 전인 상담 {data.notYetDue}건은 완료율에서 제외합니다.</p><p className="text-xs text-muted-foreground">비율은 소수점 한 자리까지 버림 표시합니다. 실제 기업의 제외 기준을 확인한 뒤 산정 기준을 확정합니다.</p></Card><section className="grid min-w-0 gap-3"><h2 className="font-semibold">집계 근거 · {data.totalItems}건</h2>{!data.items.length&&<p className="text-sm text-muted-foreground">조회 기간에 원래 기한이 속하는 상담이 없습니다.</p>}{data.items.map(i=><Card key={i.id} className="min-w-0 gap-2 p-4"><div className="flex flex-wrap justify-between gap-2"><Link to={`/live/cases/${i.id}`} className="break-words font-medium underline">{i.name}</Link><span className="text-sm">{results[i.result]}</span></div><p className="text-xs text-muted-foreground">{i.assignee} · {i.stage}{i.excluded?' · 관리 제외':''}</p><p className="text-sm">원래 기한: {date(i.originalDueAt)}<br/>현재 완료 기록: {i.completedAt?date(i.completedAt):'없음'}</p></Card>)}{data.totalItems>100&&<p className="text-sm text-muted-foreground">집계는 전체 대상 기준이며 상세는 앞 100건만 표시합니다. 기간을 좁혀 확인해 주세요.</p>}</section></>}</div>;
}
