import {randomUUID} from 'node:crypto';
import {ApiError,requireValue,fields,text,dayDeadline} from './rules.mjs';
import {describeTask} from '../../../packages/domain/task-types.ts';
import {verifyAiSource} from './ai-suggestions.mjs';

const active=c=>!c.linked_case_id&&!['종료','서비스 완료'].includes(c.stage);
const normalized=s=>s.toLowerCase().replace(/\s/g,'');

// All writes require staff review. AI suggestions are generated by a separate read-only endpoint.
export function followUpService({db,access,once,version,audit,now,caseView,taskView,aiEnv}){
  return {
    async relatedCases(user,id){
      const c=await access(db,user,id);
      requireValue(active(c),'진행 중인 영업건에서 확인해 주세요.',409);
      const {rows}=await db.query("SELECT c.*,u.name AS assignee_name FROM crm_cases c JOIN crm_users u ON u.id=c.assignee_id WHERE c.tenant_id=$1 AND ($2='admin' OR c.assignee_id=$3) AND c.id<>$4 AND c.linked_case_id IS NULL AND c.stage NOT IN ('종료','서비스 완료') AND regexp_replace(lower(c.name),'\\s','','g')=$5 ORDER BY c.received_at DESC,c.id LIMIT 20",[user.tenantId,user.role,user.id,id,normalized(c.name)]);
      return {mode:'rules',items:rows.map(row=>({...caseView(row),reason:'업체명이 같습니다. 부서·장소·요청 내용까지 같은지 직접 확인하세요.'}))};
    },
    async linkCases(user,id,body,key){
      fields(body,['targetId','expectedVersion','targetVersion','keepTaskIds','confirmed','reason']);
      requireValue(body.targetId!==id&&/^[0-9a-f-]{36}$/i.test(body.targetId),'연결할 다른 영업건을 선택하세요.');
      requireValue(body.confirmed===true,'같은 요청인지 확인해 주세요.');
      requireValue(Array.isArray(body.keepTaskIds)&&body.keepTaskIds.every(v=>typeof v==='string')&&new Set(body.keepTaskIds).size===body.keepTaskIds.length,'유지할 업무를 확인하세요.');
      const reason=text(body.reason,'같은 요청으로 판단한 이유',1000);
      return db.transaction(async tx=>{
        // Serialize linking only; normal writes still lock the affected case rows.
        if(db.driver==='postgres')await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`crm-link:${user.tenantId}`]);
        const locked={};for(const cid of [id,body.targetId].sort())locked[cid]=await access(tx,user,cid,true);
        const source=locked[id],target=locked[body.targetId];
        return once(tx,user.tenantId,user.id,`link:${id}`,key,body,async()=>{
          version(source.version,body.expectedVersion);version(target.version,body.targetVersion);
          requireValue(active(source)&&active(target),'이미 연결되었거나 종료된 영업건입니다. 새로 확인하세요.',409);
          const family=(await tx.query('SELECT id FROM crm_cases WHERE tenant_id=$1 AND (id=$2 OR linked_case_id=$2) ORDER BY id FOR UPDATE',[user.tenantId,id])).rows.map(r=>r.id);
          const tasks=(await tx.query("SELECT * FROM crm_tasks WHERE tenant_id=$1 AND case_id=ANY($2::uuid[]) ORDER BY id FOR UPDATE",[user.tenantId,family])).rows;
          const open=tasks.filter(t=>t.kind==='work'&&t.status==='incomplete'&&!t.excluded);
          requireValue(body.keepTaskIds.every(tid=>open.some(t=>t.id===tid)),'업무가 변경되었습니다. 다시 확인하세요.',409);
          const excluded=open.filter(t=>!body.keepTaskIds.includes(t.id)).map(t=>t.id);
          await tx.query("UPDATE crm_tasks SET excluded=true,version=version+1 WHERE tenant_id=$1 AND (id=ANY($2::uuid[]) OR (case_id=ANY($3::uuid[]) AND kind='first' AND status='incomplete' AND NOT excluded))",[user.tenantId,excluded,family]);
          await tx.query("UPDATE crm_tasks SET case_id=$3,version=version+1 WHERE tenant_id=$1 AND case_id=ANY($2::uuid[]) AND kind='work'",[user.tenantId,family,body.targetId]);
          await tx.query("UPDATE crm_change_proposals SET status='rejected',decided_by=$3,decided_at=$4,version=version+1 WHERE tenant_id=$1 AND case_id=ANY($2::uuid[]) AND status='pending'",[user.tenantId,family,user.id,now()]);
          await tx.query("UPDATE crm_cases SET linked_case_id=$3,stage='종료',follow_up=NULL,version=version+1 WHERE tenant_id=$1 AND id=ANY($2::uuid[])",[user.tenantId,family,body.targetId]);
          const pending={taskType:source.follow_up?.taskType||'',cause:'linked',at:now()};
          await tx.query('UPDATE crm_cases SET follow_up=$2,version=version+1 WHERE id=$1',[body.targetId,JSON.stringify(pending)]);
          const payload={reason,sourceIds:family,targetId:body.targetId,keptTaskIds:body.keepTaskIds,excludedTaskIds:excluded,beforeStage:source.stage,afterStage:'연결된 영업건에서 관리'};
          await audit(tx,user.tenantId,id,user.id,'같은 요청으로 연결',payload);
          await audit(tx,user.tenantId,body.targetId,user.id,'추가 상담 연결',payload);
          return {id:body.targetId,version:target.version+1};
        });
      });
    },
    async followUp(user,id,body,key){
      fields(body,['expectedVersion','stage','situation','createTask','taskType','description','date','confirmed','aiSource']);
      requireValue(['접수','상담 진행','제안·협의','계약 완료','서비스 진행','서비스 완료','종료'].includes(body.stage),'단계를 확인하세요.');
      requireValue(typeof body.createTask==='boolean'&&body.confirmed===true,'다음 진행안을 확인하고 승인하세요.');
      const situation=text(body.situation,'고객 상황',1000);
      let content; if(body.createTask){try{content=describeTask(text(body.taskType,'업무 종류'),text(body.description,'내용',1000,true));}catch(e){throw new ApiError(422,e.message);}}
      const dueAt=body.createTask&&body.date?dayDeadline(body.date):null;
      const closing=['종료','서비스 완료'].includes(body.stage);
      requireValue(!closing||!body.createTask,'종료할 때는 새 업무를 만들 수 없습니다.');
      return db.transaction(async tx=>{
        const c=await access(tx,user,id,true);
        return once(tx,user.tenantId,user.id,`follow-up:${id}`,key,body,async()=>{
          const aiSource=verifyAiSource(body.aiSource,user,id,body.expectedVersion,now(),aiEnv);
          version(c.version,body.expectedVersion);requireValue(active(c),'진행 중인 영업건에서 확인하세요.',409);
          requireValue(c.follow_up,'이미 다음 진행을 결정했습니다. 최신 기록을 확인하세요.',409);
          const open=(await tx.query("SELECT * FROM crm_tasks WHERE tenant_id=$1 AND case_id=$2 AND status='incomplete' AND NOT excluded",[user.tenantId,id])).rows;
          requireValue(closing||body.createTask||open.length,'다음 업무나 다시 확인할 날짜를 등록해 주세요.');
          let taskId=null;
          if(body.createTask){
            requireValue(!open.some(t=>t.task_type===content.taskType&&t.description===content.description&&String(t.due_at?new Date(t.due_at).toISOString():'')===String(dueAt||'')),'동일한 업무가 있습니다. 기존 업무 유지를 선택하세요.',409);
            taskId=randomUUID();await tx.query("INSERT INTO crm_tasks(id,tenant_id,case_id,title,task_type,description,kind,due_at,original_due_at,created_at) VALUES($1,$2,$3,$4,$5,$6,'work',$7,$7,$8)",[taskId,user.tenantId,id,content.title,content.taskType,content.description,dueAt,now()]);
          }
          await tx.query('UPDATE crm_cases SET stage=$2,follow_up=NULL,version=version+1 WHERE id=$1',[id,body.stage]);
          await audit(tx,user.tenantId,id,user.id,'다음 진행 승인',{reason:situation,beforeStage:c.stage,afterStage:body.stage,taskId,task:content||null,dueAt,remainingTaskIds:open.map(t=>t.id),source:aiSource?'ai-reviewed':'rules-reviewed',...(aiSource?{aiSource}:{})});
          return {id,version:c.version+1,taskId};
        });
      });
    },
  };
}
