import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { openDatabase } from '../src/db.mjs';
import { makeServer } from '../src/server.mjs';
import { provision } from '../src/setup.mjs';
import { createUser } from '../src/auth.mjs';

test('고객 수정·단계·담당자 변경·종료의 HTTP 권한, 미리보기, 충돌과 재시도',async t=>{
  const db=await openDatabase({url:'',directory:''}),password='Changes-test-only';
  const company=await provision(db,{password});
  const foreign=await provision(db,{password,slug:'foreign',adminEmail:'foreign@crm.local',staffEmail:'foreign-staff@crm.local'});
  const nextId=await createUser(db,{tenantId:company.tenantId,name:'새 담당 직원',email:'next@crm.local',password,role:'staff'});
  const server=makeServer(db);await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const origin=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{server.closeIdleConnections();await new Promise(r=>server.close(r));await db.close();});
  async function call(path,{method='GET',body,cookie,key=randomUUID()}={}){
    const response=await fetch(`${origin}/api/v1${path}`,{method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
    return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
  }
  async function login(email){const r=await call('/auth/login',{method:'POST',body:{email,password}});assert.equal(r.status,200);return r.cookie;}
  const staff=await login('staff@crm.local'),admin=await login('admin@crm.local'),other=await login('foreign@crm.local'),next=await login('next@crm.local');
  const inquiry={customerType:'company',name:'원래 고객사',person:'홍담당',phone:'010-0000-0000',email:'request@example.com',memo:'초기 시설 점검 요청'};
  const receipt=await call('/public/inquiries/local-review',{method:'POST',body:inquiry});
  const path=`/cases/${receipt.data.receiptId}`;
  assert.equal((await call('/assignees',{cookie:staff})).status,403);
  const employees=(await call('/assignees',{cookie:admin})).data.items;
  assert.equal(employees.length,3);assert.ok(!employees.some(u=>u.id===foreign.staffId));
  const patch={customerType:'company',name:'수정된 고객사',person:'김담당',phone:'010-1111-1111',email:'updated@example.com',size:'10~49명',requestMemo:'시설 점검과 수리 견적',reason:'고객 요청으로 연락처와 요청 내용 정정',expectedVersion:1};
  assert.equal((await call(path,{method:'PATCH',cookie:other,body:patch})).status,404);
  assert.equal((await call(path,{method:'PATCH',cookie:staff,body:{...patch,assigneeId:nextId}})).status,422);
  assert.equal((await call(path,{method:'PATCH',cookie:staff,body:{...patch,stage:'종료'}})).status,422);
  const patchKey=randomUUID(),updated=await call(path,{method:'PATCH',cookie:staff,body:patch,key:patchKey});
  assert.equal(updated.status,200,JSON.stringify(updated.data));
  assert.deepEqual((await call(path,{method:'PATCH',cookie:staff,body:patch,key:patchKey})).data,updated.data);
  let d=(await call(path,{cookie:staff})).data;
  assert.equal(d.salesCase.original.name,'원래 고객사');assert.equal(d.salesCase.original.memo,inquiry.memo);
  assert.equal(d.salesCase.requestMemo,patch.requestMemo);assert.equal(d.salesCase.name,patch.name);
  assert.equal((await call(`${path}/stage`,{method:'POST',cookie:staff,body:{stage:'종료',reason:'우회',expectedVersion:2}})).status,422);
  assert.equal((await call(`${path}/stage`,{method:'POST',cookie:staff,body:{stage:'서비스 완료',reason:'우회',expectedVersion:2}})).status,422);
  assert.equal((await call(`${path}/stage`,{method:'POST',cookie:staff,body:{stage:'상담 진행',reason:'상담 배경 확인',expectedVersion:2}})).status,200);
  const contact=(await call(path,{cookie:staff})).data.tasks[0];
  assert.equal((await call(`${path}/contacts`,{method:'POST',cookie:staff,body:{taskId:contact.id,outcome:'connected',actualAt:new Date().toISOString(),expectedVersion:1}})).status,201);
  d=(await call(path,{cookie:staff})).data;
  await call(`${path}/tasks`,{method:'POST',cookie:staff,body:{taskType:'meeting',expectedVersion:d.salesCase.version}});
  d=(await call(path,{cookie:staff})).data;
  const proposalBody={type:'reassign',reason:'담당자 부재로 인계',proposedAssigneeId:nextId,expectedVersion:d.salesCase.version};
  assert.equal((await call(`${path}/change-proposals`,{method:'POST',cookie:admin,body:{...proposalBody,proposedAssigneeId:foreign.staffId}})).status,422);
  const proposed=await call(`${path}/change-proposals`,{method:'POST',cookie:staff,body:proposalBody});assert.equal(proposed.status,201);
  const pp=`/change-proposals/${proposed.data.id}`;
  assert.equal((await call(path,{cookie:staff})).data.salesCase.assigneeId,company.staffId);
  assert.equal((await call('/workboard',{cookie:staff})).data.needsReview.length,1);
  assert.equal((await call(`${pp}/preview`,{cookie:other})).status,404);
  const preview=(await call(`${pp}/preview`,{cookie:staff})).data;
  assert.equal(preview.openTasks.length,1);assert.equal(preview.proposedAssignee.id,nextId);assert.equal(preview.canDecide,false);
  const approveBody={expectedCaseVersion:preview.salesCase.version,expectedProposalVersion:preview.proposal.version,confirmed:true};
  assert.equal((await call(`${pp}/approve`,{method:'POST',cookie:staff,body:approveBody})).status,403);
  assert.equal((await call(`${pp}/approve`,{method:'POST',cookie:admin,body:{...approveBody,confirmed:false}})).status,422);
  await db.query('UPDATE crm_users SET active=false WHERE id=$1',[nextId]);
  assert.equal((await call(`${pp}/approve`,{method:'POST',cookie:admin,body:approveBody})).status,422);
  assert.equal((await call(`${pp}/preview`,{cookie:admin})).data.proposedAssignee.active,false);
  await db.query('UPDATE crm_users SET active=true WHERE id=$1',[nextId]);
  await call(`${path}/notes`,{method:'POST',cookie:staff,body:{body:'확인 중 추가 메모',expectedVersion:preview.salesCase.version}});
  assert.equal((await call(`${pp}/approve`,{method:'POST',cookie:admin,body:approveBody})).status,409);
  const fresh=(await call(`${pp}/preview`,{cookie:admin})).data;
  const freshBody={...approveBody,expectedCaseVersion:fresh.salesCase.version};const approveKey=randomUUID();
  const approved=await call(`${pp}/approve`,{method:'POST',cookie:admin,body:freshBody,key:approveKey});assert.equal(approved.status,200);
  assert.deepEqual((await call(`${pp}/approve`,{method:'POST',cookie:admin,body:freshBody,key:approveKey})).data,approved.data);
  assert.equal((await call(path,{cookie:staff})).status,404);
  assert.equal((await call('/workboard',{cookie:staff})).data.needsReview.length,0);
  assert.equal((await call('/workboard',{cookie:next})).data.needsReview.length,1);
  d=(await call(path,{cookie:next})).data;
  assert.equal(d.tasks.find(t=>t.kind==='first').completedBy,company.staffId);
  const closing=await call(`${path}/change-proposals`,{method:'POST',cookie:next,body:{type:'close',reason:'고객이 진행 취소',expectedVersion:d.salesCase.version}});
  assert.equal((await call('/workboard',{cookie:next})).data.needsReview.length,1);
  const cp=`/change-proposals/${closing.data.id}`,closePreview=(await call(`${cp}/preview`,{cookie:next})).data;
  const closeKey=randomUUID(),closeBody={expectedCaseVersion:closePreview.salesCase.version,expectedProposalVersion:1,confirmed:true};
  const closed=await call(`${cp}/approve`,{method:'POST',cookie:next,body:closeBody,key:closeKey});assert.equal(closed.status,200);
  assert.deepEqual((await call(`${cp}/approve`,{method:'POST',cookie:next,body:closeBody,key:closeKey})).data,closed.data);
  assert.equal((await call('/workboard',{cookie:next})).data.needsReview.length,0);
  d=(await call(path,{cookie:next})).data;
  assert.equal(d.salesCase.stage,'종료');assert.equal(d.tasks.find(t=>t.kind==='work').status,'incomplete');
  assert.equal((await call(`${path}/notes`,{method:'POST',cookie:next,body:{body:'종료 후 쓰기',expectedVersion:d.salesCase.version}})).status,409);
  assert.equal(d.activities.filter(a=>a.action==='영업건 종료 확정').length,1);
  assert.equal(d.activities.filter(a=>a.action==='담당자 변경 확정').length,1);

  const receipt2=await call('/public/inquiries/local-review',{method:'POST',body:inquiry});const second=`/cases/${receipt2.data.receiptId}`;
  const rejectProposal=await call(`${second}/change-proposals`,{method:'POST',cookie:staff,body:{type:'service_complete',reason:'완료 요청',expectedVersion:1}});
  const rejectPath=`/change-proposals/${rejectProposal.data.id}`;
  assert.equal((await call(`${rejectPath}/reject`,{method:'POST',cookie:staff,body:{expectedCaseVersion:1,expectedProposalVersion:1,reason:'잔여 작업 확인 필요'}})).status,200);
  assert.equal((await call(second,{cookie:staff})).data.salesCase.stage,'접수');
  const completeProposal=await call(`${second}/change-proposals`,{method:'POST',cookie:staff,body:{type:'service_complete',reason:'서비스 제공 종료 확인',expectedVersion:1}});
  assert.equal((await call(`/change-proposals/${completeProposal.data.id}/approve`,{method:'POST',cookie:staff,body:{expectedCaseVersion:1,expectedProposalVersion:1,confirmed:true}})).status,200);
  assert.equal((await call(second,{cookie:staff})).data.salesCase.stage,'서비스 완료');
});
