import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import { openDatabase } from '../src/db.mjs';
import { makeServer } from '../src/server.mjs';
import { provision } from '../src/setup.mjs';
import { createUser } from '../src/auth.mjs';
import { createService } from '../src/service.mjs';
import { firstDeadline } from '../src/rules.mjs';

const inquiry={customerType:'company',name:'검수 고객',person:'고객 담당자',phone:'010-1234-5678',email:'customer@example.com',memo:'정기 점검 견적을 요청합니다.'};
test('첫 연락 기한은 한국 시간의 다음 영업일 17시이며 주말과 설정 휴일을 제외한다',()=>{
  assert.equal(firstDeadline('2026-09-11T07:00:00Z',[]),'2026-09-14T08:00:00.000Z');
  assert.equal(firstDeadline('2026-09-11T07:00:00Z',['2026-09-14']),'2026-09-15T08:00:00.000Z');
  assert.equal(firstDeadline('2026-09-12T07:00:00Z',[]),'2026-09-14T08:00:00.000Z');
});

test('HTTP 로그인, 회사·담당자 권한, 원자적 저장, 재시도, 연락 기준과 동시 변경 검수',async t=>{
  const db=await openDatabase({url:'',directory:''});
  let at=new Date('2026-09-11T07:00:00Z');
  const password='Test-only-password-123';
  const first=await provision(db,{password});
  await provision(db,{password,slug:'another-company',adminEmail:'admin2@crm.local',staffEmail:'staff2@crm.local'});
  await createUser(db,{tenantId:first.tenantId,name:'다른 직원',email:'other@crm.local',password,role:'staff'});
  const server=makeServer(db,{clock:()=>at});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const origin=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{server.closeIdleConnections();await new Promise(r=>server.close(r));await db.close();});
  async function call(path,{method='GET',body,cookie,key=randomUUID(),source=origin}={}){
    const response=await fetch(`${origin}/api/v1${path}`,{method,headers:{Origin:source,'Content-Type':'application/json','Idempotency-Key':key,...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
    return {status:response.status,data:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
  }
  async function signIn(email){const r=await call('/auth/login',{method:'POST',body:{email,password}});assert.equal(r.status,200);return r.cookie;}
  assert.equal((await call('/cases')).status,401);
  assert.equal((await call('/auth/login',{method:'POST',body:{email:'staff@crm.local',password:'wrong'}})).status,401);
  const staff=await signIn('staff@crm.local'),admin=await signIn('admin@crm.local'),other=await signIn('other@crm.local'),foreign=await signIn('admin2@crm.local');
  assert.equal((await call('/auth/logout',{method:'POST',cookie:staff,source:'http://evil.example'})).status,403);
  const receiptKey=randomUUID();
  const receipt=await call('/public/inquiries/local-review',{method:'POST',body:inquiry,key:receiptKey});
  assert.equal(receipt.status,201,JSON.stringify(receipt.data));
  assert.equal(receipt.data.firstContactDueAt,'2026-09-14T08:00:00.000Z');
  const duplicate=await call('/public/inquiries/local-review',{method:'POST',body:inquiry,key:receiptKey});
  assert.deepEqual(duplicate.data,receipt.data);
  assert.equal((await call('/public/inquiries/local-review',{method:'POST',body:{...inquiry,name:'다른 요청'},key:receiptKey})).status,409);
  assert.equal((await call('/public/inquiries/local-review',{method:'POST',body:{...inquiry,tenantId:first.tenantId}})).status,422);
  const id=receipt.data.receiptId, path=`/cases/${id}`;
  assert.equal((await call('/cases',{cookie:staff})).data.items.length,1);
  assert.equal((await call('/cases',{cookie:other})).data.items.length,0);
  assert.equal((await call('/cases',{cookie:foreign})).data.items.length,0);
  assert.equal((await call(path,{cookie:other})).status,404);
  assert.equal((await call(path,{cookie:foreign})).status,404);
  assert.equal((await call(path,{cookie:admin})).status,200);
  let detail=(await call(path,{cookie:staff})).data;
  assert.equal(detail.tasks.length,1);
  assert.equal(detail.salesCase.assigneeId,first.staffId);
  const task=detail.tasks[0];
  assert.equal((await call('/workboard',{cookie:staff})).data.today.length,1);
  const noteBody={body:'권한 없는 작성',expectedVersion:1};
  assert.equal((await call(`${path}/notes`,{method:'POST',cookie:other,body:noteBody})).status,404);
  assert.equal((await call(`/tasks/${task.id}`,{method:'PATCH',cookie:foreign,body:{date:'2026-09-15',reason:'변경',expectedVersion:1}})).status,404);
  assert.equal((await call(`/tasks/${task.id}/complete`,{method:'POST',cookie:staff,body:{actualAt:at.toISOString(),expectedVersion:1}})).status,422);
  at=new Date('2026-09-11T07:02:00Z');
  assert.equal((await call(`${path}/contacts`,{method:'POST',cookie:staff,body:{taskId:task.id,outcome:'connected',actualAt:'2026-09-11T08:00:00Z',expectedVersion:1}})).status,422);
  const attemptBody={taskId:task.id,outcome:'attempt',actualAt:at.toISOString(),expectedVersion:1};
  const attemptKey=randomUUID();
  const attempt=await call(`${path}/contacts`,{method:'POST',cookie:staff,body:attemptBody,key:attemptKey});
  assert.equal(attempt.status,201,JSON.stringify(attempt.data));
  assert.deepEqual((await call(`${path}/contacts`,{method:'POST',cookie:staff,body:attemptBody,key:attemptKey})).data,attempt.data);
  detail=(await call(path,{cookie:staff})).data;
  assert.equal(detail.tasks[0].status,'incomplete');
  assert.equal(detail.tasks[0].version,2);
  assert.equal((await db.query('SELECT count(*)::int AS n FROM crm_contacts')).rows[0].n,1);
  assert.equal((await call(`${path}/contacts`,{method:'POST',cookie:staff,body:{...attemptBody,outcome:'connected'}})).status,409);
  const connected=await call(`${path}/contacts`,{method:'POST',cookie:staff,body:{...attemptBody,outcome:'connected',memo:'미팅 일정 협의 예정',expectedVersion:2}});
  assert.equal(connected.status,201);
  detail=(await call(path,{cookie:staff})).data;
  assert.equal(detail.tasks[0].status,'complete');
  assert.equal(detail.salesCase.stage,'상담 진행');
  assert.equal(detail.notes[0].body,'미팅 일정 협의 예정');
  assert.equal((await call('/workboard',{cookie:staff})).data.today.length,0);
  const noteRequests=await Promise.all(['첫 메모','동시 메모'].map(body=>call(`${path}/notes`,{method:'POST',cookie:staff,body:{body,expectedVersion:detail.salesCase.version}})));
  assert.deepEqual(noteRequests.map(r=>r.status).sort(),[201,409]);
  detail=(await call(path,{cookie:staff})).data;
  assert.equal(detail.notes.length,2);
  const expectedVersion=detail.salesCase.version;
  assert.equal((await call(`${path}/tasks`,{method:'POST',cookie:staff,body:{taskType:'other',expectedVersion}})).status,422);
  const added=await call(`${path}/tasks`,{method:'POST',cookie:staff,body:{taskType:'meeting',description:'방문 가능한 시간 확인',expectedVersion}});
  assert.equal(added.status,201,JSON.stringify(added.data));
  assert.equal((await call('/workboard',{cookie:staff})).data.needsReview.length,1);
  let taskId=added.data.id;
  assert.equal((await call(`/tasks/${taskId}`,{method:'PATCH',cookie:staff,body:{date:'2026-09-15',reason:'고객과 일정 협의',expectedVersion:1}})).status,200);
  assert.equal((await call(`/tasks/${taskId}`,{method:'PATCH',cookie:staff,body:{date:'2026-09-16',reason:'고객 요청으로 하루 연기',expectedVersion:2}})).status,200);
  detail=(await call(path,{cookie:staff})).data;
  const changed=detail.tasks.find(t=>t.id===taskId);
  assert.equal(changed.originalDueAt,'2026-09-15T08:00:00.000Z');
  assert.equal(changed.dueAt,'2026-09-16T08:00:00.000Z');
  assert.equal((await call(`/tasks/${taskId}/complete`,{method:'POST',cookie:staff,body:{actualAt:at.toISOString(),expectedVersion:3}})).status,200);
  assert.equal((await call(`/tasks/${taskId}/reopen`,{method:'POST',cookie:staff,body:{reason:'잘못 완료 처리',expectedVersion:4}})).status,200);
  assert.equal((await call(`/tasks/${taskId}/exclude`,{method:'POST',cookie:staff,body:{reason:'고객이 요청 취소',expectedVersion:5}})).status,200);
  detail=(await call(path,{cookie:staff})).data;
  assert.equal(detail.tasks.find(t=>t.id===taskId).excluded,true);
  assert.deepEqual(detail.salesCase.original.memo,inquiry.memo);
  assert.ok(detail.activities.some(a=>a.action==='완료 취소'&&a.payload.reason==='잘못 완료 처리'));
  const secondReceipt=await call('/public/inquiries/local-review',{method:'POST',body:{...inquiry,name:'부재중 고객'}});
  const secondPath=`/cases/${secondReceipt.data.receiptId}`;
  const secondDetail=(await call(secondPath,{cookie:staff})).data;
  assert.equal((await call(`${secondPath}/contacts`,{method:'POST',cookie:staff,body:{taskId:secondDetail.tasks[0].id,outcome:'sms',actualAt:at.toISOString(),expectedVersion:1}})).status,201);
  const smsDetail=(await call(secondPath,{cookie:staff})).data;
  assert.equal(smsDetail.tasks[0].status,'complete');
  assert.equal(smsDetail.salesCase.stage,'접수');
  assert.equal((await call('/auth/logout',{method:'POST',cookie:staff})).status,200);
  assert.equal((await call('/auth/me',{cookie:staff})).status,401);
  at=new Date('2026-09-12T07:00:00Z');
  assert.equal((await call('/auth/me',{cookie:admin})).status,401);
});

test('파일 DB를 닫았다 다시 열어도 상담·업무·중복 방지 결과가 유지된다',async()=>{
  const root=await mkdtemp(join(tmpdir(),'crm-persistence-test-'));
  const directory=join(root,'db');let db;
  try {
    db=await openDatabase({url:'',directory});
    await provision(db,{password:'Local-test-password'});
    const key=randomUUID();
    const receipt=await createService(db).intake('local-review',inquiry,key);
    await db.close();db=await openDatabase({url:'',directory});
    assert.deepEqual(await createService(db).intake('local-review',inquiry,key),receipt);
    assert.equal((await db.query('SELECT count(*)::int AS n FROM crm_cases')).rows[0].n,1);
    assert.equal((await db.query('SELECT count(*)::int AS n FROM crm_tasks')).rows[0].n,1);
    assert.equal((await db.query('SELECT count(*)::int AS n FROM crm_notification_jobs')).rows[0].n,2);
  } finally {
    if(db)await db.close();
    const target=resolve(root),base=resolve(tmpdir())+sep;
    assert.ok(target.startsWith(base)&&target.slice(base.length).startsWith('crm-persistence-test-'));
    await rm(target,{recursive:true,force:true});
  }
});
